### ISSUE TITLE
[suggestion] more reliance on mixins, less on importing everything and making changes in variables file

### ISSUE THREAD

**Issue by architarious** [wvuweb/wvu-brand-patterns-theme#21]
Would be a less confusing and would make lighter footprints in CSS code (for those not using every pattern) if blocks where implemented via just the mixins than with mixins + the variables.scss file.

For example instead of doing this to implement just the masthead:
```scss
@import 'wvu-patterns/0-plugins/plugins-dir';
@import 'wvu-patterns/1-base/base-dir';
@import 'wvu-patterns/2-modules/modules-dir';
@import 'wvu-patterns/3-layouts/layouts-dir';

wvu-patterns/1-base/_variables.scss : 
 $wvu-masthead-two-line-lockup: true;
 $wvu-masthead-has-signature: true;
```

we could do this instead:
```scss
@import 'wvu-patterns/1-base/wvu-masthead';
@include wvu-masthead-is-two-line-lockup();
@include wvu-masthead-has-signature();
```

By setting up your mixins to recognize inputs
```scss
@mixin wvu-masthead-is-two-line-lockup( $wvu-masthead-two-line-lockup: true) {
  @if $wvu-masthead-two-line-lockup == true {
    .wvu-masthead__title { font-size: 0.75em; line-height: 1.08333333em; float: left; margin-top: 0.1em; }
    .wvu-masthead__university-name { top: 7.1em; }
  }
}
```

and by including any relevant variables or imports in the _wvu-masthead.scss file
```scss
@import '../0-plugins/wvu-utilities/media-queries';

// Breakpoints
//==================================================

$bp-mini: 450;
$bp-small: 570;
$bp-medium: 768;
$bp-large: 960;
$bp-xlarge: 1200;
```
