### ISSUE TITLE
Provide PNG fallbacks for SVG background images

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/wvu-brand-patterns-theme#4]
This is probably part of your IE8 support, but IE8 doesn't understand SVG's in background images:

So, you might have something like this:

```css
.example {
  background-image: url(../images/logo.svg);
}
```

and it should change to this:

```css
.example {
  background-image: url(../images/logo.png);
  background-image: url(../images/logo.svg);
}
```
